version: "3.9"
services:
  db:
    image: postgres:16
    container_name: taskflow_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskflow
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d taskflow"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  dbdata:
